"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from dotenv import load_dotenv
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "unsafe-local-development-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]


def _csv_env(name: str, default: str = "") -> list[str]:
    """Parse comma-separated env values into a clean list."""
    return [value.strip() for value in os.getenv(name, default).split(",") if value.strip()]


def _normalize_origin(origin: str) -> str:
    """CORS/CSRF origins must not include a trailing slash."""
    return origin.strip().rstrip("/")

# Application definition

INSTALLED_APPS = [
    # Django built-in apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    # django-storages provides the S3Boto3Storage backend used when USE_S3=True
    'storages',

    # Local apps
    'users',
    'plots',
    'inventory',
    'help_requests',
    'notifications',
    'weather',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Neon integration implemented
database_url = os.getenv("DATABASE_URL", "sqlite:///db.sqlite3")

DATABASES = {
    "default": dj_database_url.config(
        default=database_url,
        conn_max_age=600,
        ssl_require=database_url.startswith("postgres") if database_url else False,
    )
}

AUTH_USER_MODEL = "users.User"

# Notification delivery
EMAIL_PROVIDER = os.getenv("EMAIL_PROVIDER", "console")

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)

NOTIFICATIONS_EMAIL_SENDER = os.getenv("NOTIFICATIONS_EMAIL_SENDER")

NOTIFICATIONS_WEBHOOK_TOKEN = os.getenv("NOTIFICATIONS_WEBHOOK_TOKEN", "")

NOTIFICATIONS_AWS_REGION = os.getenv(
    "AWS_SES_REGION",
    "us-west-2",
)

# --- Media storage (local disk by default; AWS S3 when USE_S3=True) ---
# Reuses the same AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY as SES.
# boto3 reads those env vars automatically for both SES and S3 clients.
USE_S3 = os.getenv("USE_S3", "False").lower() == "true"

# Shared region for S3; defaults to the SES region so one account stays aligned.
AWS_S3_REGION_NAME = os.getenv(
    "AWS_S3_REGION_NAME",
    os.getenv("AWS_SES_REGION", "us-west-2"),
)

# Bucket that holds uploaded plot photos and other media files.
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "")

# Optional CloudFront / custom domain; leave empty to use the default S3 URL.
AWS_S3_CUSTOM_DOMAIN = os.getenv("AWS_S3_CUSTOM_DOMAIN", "").strip()

# Keep original filenames unique enough by never overwriting same-key objects.
AWS_S3_FILE_OVERWRITE = False

# Let the bucket policy own ACLs (private bucket + app-side auth recommended).
AWS_DEFAULT_ACL = None

# Signed URLs for private objects; set False only if the bucket/objects are public.
AWS_QUERYSTRING_AUTH = os.getenv("AWS_QUERYSTRING_AUTH", "True").lower() == "true"

# Object key prefix inside the bucket (keeps media separate from other assets).
AWS_LOCATION = os.getenv("AWS_LOCATION", "media")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / "staticfiles"

# Local uploads land here when USE_S3 is false (DEBUG also serves them via urls.py).
MEDIA_ROOT = BASE_DIR / "media"

if USE_S3:
    # Production/staging: Django FileField/ImageField writes go to S3 via django-storages.
    # Credentials come from AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY (same as SES).
    if AWS_S3_CUSTOM_DOMAIN:
        # Prefer a CDN/custom domain when configured.
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/"
    else:
        # Default virtual-hosted–style S3 URL for the configured region/bucket.
        MEDIA_URL = (
            f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}"
            f".amazonaws.com/{AWS_LOCATION}/"
        )

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    # Local/dev: keep uploads on disk so S3 is optional during development.
    MEDIA_URL = "/media/"

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Local Vite dev servers (5173, 5174, 5175, etc.)
CORS_ALLOWED_ORIGIN_REGEXES = _csv_env(
    "CORS_ALLOWED_ORIGIN_REGEXES",
    r"^http://localhost:517\d$,^http://127\.0\.0\.1:517\d$",
)

# Explicit origins (production, staging, etc.)
CORS_ALLOWED_ORIGINS = [
    _normalize_origin(origin)
    for origin in _csv_env("CORS_ALLOWED_ORIGINS")
]

# Keep CSRF trusted origins aligned with explicit CORS origins unless overridden.
CSRF_TRUSTED_ORIGINS = [
    _normalize_origin(origin)
    for origin in _csv_env(
        "CSRF_TRUSTED_ORIGINS",
        ",".join(CORS_ALLOWED_ORIGINS),
    )
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    # Auth email endpoints set throttle_classes explicitly; rates live here.
    "DEFAULT_THROTTLE_RATES": {
        "auth_register": "10/hour",
        "auth_resend_ip": "10/hour",
        "auth_resend_email": "3/hour",
    },
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# --- Email (console locally; AWS SES SMTP in production) ---
# Dev default prints messages to the runserver console.
# For SES: set EMAIL_BACKEND to django.core.mail.backends.smtp.EmailBackend
# and EMAIL_HOST to email-smtp.<region>.amazonaws.com with SES SMTP credentials.
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "Judkins Park P-Patch <noreply@example.com>",
)
# Used in confirmation links emailed to new registrants.
# Prefer "localhost" over 127.0.0.1 — Vite often binds IPv6 localhost only.
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173").strip().rstrip("/")
