# Generated by Django 5.2.16 on 2026-08-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('claimed', 'Claimed'), ('done', 'Done')], default='active', max_length=10),
        ),
    ]
