# Generated by Django 5.2.16 on 2026-08-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_requests', '0002_alter_helprequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('done', 'Done')], default='active', max_length=10),
        ),
    ]
