# Generated by Django 5.2.16 on 2026-07-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='name',
            new_name='item',
        ),
    ]
