# Generated by Django 5.2.16 on 2026-07-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_name_inventoryitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
