# Generated by Django 5.2.16 on 2026-08-05 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_inventoryitem_quantity"),
        ("plots", "0002_garden_latitude_garden_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="garden",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_items",
                to="plots.garden",
            ),
        ),
    ]
